### PR TITLE
An example comparison for docs

### PR DESCRIPTION
**Pull request by fortrustit**
test

- [ ] 

- [ ]

### CODE REVIEW

**Review by aboooodecool — COMMENTED** [review]
https://github.com/nasirxo/flb2/blob/master/README.md

**Comment by aboooodecool** [comment]
https://github.com/nasirxo/flb2/blob/master/README.md

**Comment by gallogit** [comment]
> prueba
> 
> * []
> * []

Open

**Comment by Shehane22** [comment]
> `
[github-statement-against-modern-slavery-and-child-labor.pdf](https://github.com/octocat/linguist/files/8571580/github-statement-against-modern-slavery-and-child-labor.pdf)
`

**Comment by ghost** [comment]
Martyb166

**Review by dubaiekpendu-lab — COMMENTED** [review]
My future daily base

**Pull request closed without merging**
